### ISSUE TITLE
add a section to "star the repo" in README.md

### ISSUE THREAD

**Issue by arujjval** [arujjval/tic-tac-toe#10]
Add a section in README.md to encourage contributors and someone who visited to like the repo if they liked it. You can check other repos to determine where and how to mention them in the file.

**Comment by 1-SubhamSingh** [comment]
I'll complete this task , can you please assign me this :)

**Comment by arujjval** [comment]
Sure. Good luck!

**Comment by sunny7899** [comment]
hi @arujjval can u assign some task to me so that i can contribute.

**Comment by 1-SubhamSingh** [comment]
@Shashank1618 , I hope you know the basic guidelines of Open Source Contribution, 
If a task is not assigned to you , you are not supposed to intefere in that task assigned to someone else.
I hope you are here to contribute to society and not to steal someone else's task as you also opened a PR for another issue not assigned to you in this project.

Respectfully , close the PR :)

**Comment by Shashank1618** [comment]
@1-SubhamSingh there is some sort of misunderstanding from my side. I hope you don't mind it. I had fixed the issue #9 and so that it will be easy for me to solve issue #10 also it doesn't require much time to solve it. 
I don't see that it was previously assigned. 
I am also here to contribute and by stealing some mere issues don't add value to my knowledge
So. here I am closing my PR for this issue

**Comment by Shashank1618** [comment]
@arujjval  If I already solve this issue will it be okay if raise a PR.

**Comment by 1-SubhamSingh** [comment]
> @arujjval If I already solve this issue will it be okay if raise a PR.

@Shashank1618 It's good that you asked this , I have no problem if the maintainer allows you.👍 

And I don't know about your knowledge but hopefully you will follow the basic rules from next time.
